### ISSUE TITLE
Console project doesn't build

### ISSUE THREAD

**Issue by MisinformedDNA** [swgoh-utils/swgoh-ae2#5]
I opened the repo in Codespaces and tried to build the console project and the solution and they both fail due to issues with AssetStudio.

> /workspaces/swgoh-ae2/AssetGetterTools/helpers/Exporter.cs(1,7): error CS0246: The type or namespace name 'AssetStudio' could not be found (are you missing a using directive or an assembly reference?) [/workspaces/swgoh-ae2/AssetGetterTools/AssetGetterTools.csproj]
/workspaces/swgoh-ae2/AssetGetterTools/helpers/Filehelper.cs(6,7): error CS0246: The type or namespace name 'AssetStudio' could not be found (are you missing a using directive or an assembly reference?) [/workspaces/swgoh-ae2/AssetGetterTools/AssetGetterTools.csproj]

Note: Swagger was working fine, but I couldn't find the image for Gyrda Keypads (it should be called something like "scavenger_gyrdakeypad", but it's not in the list). So I was going to download all the images so I could see if it was named weird.

**Comment by MisinformedDNA** [comment]
Ah, I had to clone the submodule

```
git submodule update --init --recursive
```

Now I get this error:

> .../SwgohAssetGetterConsole/bin/Debug/net6.0 (main) $ dotnet SwgohAssetGetterConsoleStudio.dll
> Checking for file /usr/local/dotnet/7.0.302/x64/Texture2DDecoderNative.dll
> Unhandled exception. System.Exception: The File Texture2DDecoderNative.dll could not be found. Make sure it exists in the folder '/usr/local/dotnet/7.0.302/x64'
>    at AssetGetterTools.Filehelper.verifytextureDLLisReady() in /workspaces/swgoh-ae2/AssetGetterTools/helpers/Filehelper.cs:line 126
>    at AssetGetterTools.Filehelper..ctor() in /workspaces/swgoh-ae2/AssetGetterTools/helpers/Filehelper.cs:line 19
>    at SwgohAssetGetterConsole.MainProgram..ctor() in /workspaces/swgoh-ae2/SwgohAssetGetterConsole/MainProgram.cs:line 41
>    at SwgohAssetGetterConsole.Program.Main(String[] args) in /workspaces/swgoh-ae2/SwgohAssetGetterConsole/consoleStart.cs:line 13
> Aborted (core dumped)
> .../SwgohAssetGetterConsole/bin/Debug/net6.0 (main) $ 

The `x64` directory does not exist where it is looking, but it does exist in the output directory `SwgohAssetGetterConsole/bin/Debug/net6.0`.

Similar error on Windows with the CLI:

> ❯ dotnet .\SwgohAssetGetterConsoleStudio.dll
> Checking for file C:\Program Files\dotnet\x64/Texture2DDecoderNative.dll
> Unhandled exception. System.Exception: The File Texture2DDecoderNative.dll could not be found. Make sure it exists in the folder 'C:\Program Files\dotnet\x64'
>    at AssetGetterTools.Filehelper.verifytextureDLLisReady() in C:\repos\swgoh-ae2\AssetGetterTools\helpers\Filehelper.cs:line 126
>    at AssetGetterTools.Filehelper..ctor() in C:\repos\swgoh-ae2\AssetGetterTools\helpers\Filehelper.cs:line 19
>    at SwgohAssetGetterConsole.MainProgram..ctor() in C:\repos\swgoh-ae2\SwgohAssetGetterConsole\MainProgram.cs:line 41
>    at SwgohAssetGetterConsole.Program.Main(String[] args) in C:\repos\swgoh-ae2\SwgohAssetGetterConsole\consoleStart.cs:line 13

But then it built fine in VS.

**Comment by SdtBarbarossa** [comment]
Hello MisinformedDNA,

first of all this Project was meaned to be used on Windows, but it may be able to be runned on other OS.

1. Yes you did the correct thing with the Submodule. Submodules are basically repos inside of repose that have his source on another origin.

2. for the Texture2DDecoderNative.dll you either copy the existing one into the correct folder, or you build one on your OS yourself. The needed C++ Project is also Part of the Submodule:
https://github.com/SdtBarbarossa/AssetStudio/tree/1c87a7b1b99b60d72280b8f5562bb43f72ead36c/Texture2DDecoderNative

3. Regrading the "scavenger_gyrdakeypad" texture you are looking for. There is a "List" Endpoint that tells you wich textures Are Available. And then you can Download this one via Single or use the GUI.

I Hope this Helps you.

Also you may want to Join the Commlink Discord Server for faster Support:

https://discord.gg/FqE6EHaZ

On this Server we Discuss everything related to Commlink(a API for swgoh), The Crinolos Stats and swgoh-ae2

**Comment by SdtBarbarossa** [comment]
Havent heard back in a while. Please open a new case if you still get errors.
